import BackArrow from './BackArrow';
import Benefits from './Benefits';
import CopySVG from './CopyButton';
import Details from './Details';
import MonthlyPay from './MonthlyPay';
import Notifications from './Notifications';
import Policy1 from './Policy1';
import Policy2 from './Policy2';
import BackSpaceSVG from './SVG/BackSpaceSVG';
import ChangeSVG from './SVG/ChangeSVG';
import ChartSVG from './SVG/ChartSVG';
import ClaimSVG from './SVG/ClaimSVG';
import CloseSVG from './SVG/CloseSVG';
import DocSVG from './SVG/DocSVG';
import HomeSVG from './SVG/HomeSVG';
import LegalSVG from './SVG/LegalSVG';
import MemberSVG from './SVG/MemberSVG';
import MiniArrow from './SVG/MiniArrowSVG';
import NarrowSVG from './SVG/NarrowSVG';
import NewBackArrow from './SVG/NewBackArrowSVG';
import NotificationSVG from './SVG/NotificationSVG';
import PaymentSVG from './SVG/PaymentSVG';
import ReceiptSVG from './SVG/ReceiptSVG';
import ScanSVG from './SVG/ScanSVG';
import SecuritySVG from './SVG/SecuritySVG';
import SettingsSVG from './SVG/SettingsSVG';
import ShareSVG from './ShareButton';
import StatementSVG from './SVG/StatementSVG';
import SupportSVG from './SVG/SupportSVG';
import Transactions1 from './Transactions1';
import Transactions2 from './Transactions2';
import Transactions3 from './Transactions3';
import WideSVG from './SVG/WideSVG';
import ClaimButton from './claimButton';
import TrophySVG from './SVG/TrophySVG';
import UmbrellaSVG from './SVG/UmbrellaSVG';
import WatchSVG from './SVG/WatchSVG';
import LogoSVG from './SVG/LogoSVG';
import GoogleWalletSVG from './SVG/GoogleWalletSVG';


export { BackArrow, BackSpaceSVG, Benefits, ChangeSVG, ChartSVG, ClaimButton, ClaimSVG, CloseSVG, CopySVG, Details, DocSVG, HomeSVG, LegalSVG, MemberSVG, MiniArrow, MonthlyPay, NarrowSVG, NewBackArrow, Notifications, NotificationSVG, PaymentSVG, Policy1, Policy2, ReceiptSVG, ScanSVG, SecuritySVG, SettingsSVG, ShareSVG, StatementSVG, SupportSVG, Transactions1, Transactions2, Transactions3, WideSVG, TrophySVG, UmbrellaSVG, WatchSVG, LogoSVG, GoogleWalletSVG };

